
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springmvc
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
 
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8081 # Change this if you want to use a different port

# Other application-specific properties can be added below

